from format import style, text, back
print('{}===== STYLES ====={}'.format(style['negrito'], style['reset']))
print('{}Negrito{}'.format(style['negrito'], style['reset']))
print('{}Sublinhado{}'.format(style['sublinhado'], style['reset']))
print('{}Negativo{}'.format(style['negativo'], style['reset']))
print('')
print('{}===== TEXT COLORS ====={}'.format(style['negrito'], style['reset']))
print('{}Branco{}'.format(text['branco'], text['reset']))
print('{}Vermelho{}'.format(text['vermelho'], text['reset']))
print('{}Vermelho claro{}'.format(text['vermelho claro'], text['reset']))
print('{}Verde{}'.format(text['verde'], text['reset']))
print('{}Verde claro{}'.format(text['verde claro'], text['reset']))
print('{}Amarelo{}'.format(text['amarelo'], text['reset']))
print('{}Amarelo claro{}'.format(text['amarelo claro'], text['reset']))
print('{}Azul{}'.format(text['azul'], text['reset']))
print('{}Azul claro{}'.format(text['azul claro'], text['reset']))
print('{}Magenta{}'.format(text['magenta'], text['reset']))
print('{}Magenta claro{}'.format(text['magenta claro'], text['reset']))
print('{}Ciano{}'.format(text['ciano'], text['reset']))
print('{}Ciano claro{}'.format(text['ciano claro'], text['reset']))
print('{}Cinza{}'.format(text['cinza'], text['reset']))
print('{}Cinza escuro{}'.format(text['cinza escuro'], text['reset']))
print('{}Preto{}'.format(text['preto'], text['reset']))
print('')
print('{}===== BACKGROUND COLORS ====={}'.format(style['negrito'], style['reset']))
print('{}Branco{}'.format(back['branco'], back['reset']))
print('{}Vermelho{}'.format(back['vermelho'], back['reset']))
print('{}Vermelho claro{}'.format(back['vermelho claro'], back['reset']))
print('{}Verde{}'.format(back['verde'], back['reset']))
print('{}Verde claro{}'.format(back['verde claro'], back['reset']))
print('{}Amarelo{}'.format(back['amarelo'], back['reset']))
print('{}Amarelo claro{}'.format(back['amarelo claro'], back['reset']))
print('{}Azul{}'.format(back['azul'], back['reset']))
print('{}Azul claro{}'.format(back['azul claro'], back['reset']))
print('{}Magenta{}'.format(back['magenta'], back['reset']))
print('{}Magenta claro{}'.format(back['magenta claro'], back['reset']))
print('{}Ciano{}'.format(back['ciano'], back['reset']))
print('{}Ciano claro{}'.format(back['ciano claro'], back['reset']))
print('{}Cinza{}'.format(back['cinza'], back['reset']))
print('{}Cinza escuro{}'.format(back['cinza escuro'], back['reset']))
print('{}Preto{}'.format(back['preto'], back['reset']))
